<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<title>Student Registration Form </title>';
echo '<style>';
echo 'form {';
echo 'margin: auto;';
echo 'width: min(600px, 80%);';
echo 'padding: 20px;';
echo 'border: 1px solid #ddd;';
echo 'border-radius: 10px;';
echo '}';
echo '';
echo 'h2 {';
echo 'text-align: center;';
echo 'font-size: 28px;';
echo 'margin-bottom: 20px;';
echo '}';
echo '';
echo 'label {';
echo 'display: block;';
echo 'margin-bottom: 5px;';
echo 'font-weight: bold;';
echo '}';
echo '';
echo 'input[type="text"],';
echo 'input[type="email"],';
echo 'input[type="datetime-local"],';
echo 'input[type="file"],';
echo 'textarea,';
echo 'select,';
echo '#dob {';
echo 'width: 100%;';
echo 'padding: 10px;';
echo 'margin-bottom: 20px;';
echo 'border: 1px solid #ddd;';
echo 'border-radius: 5px;';
echo 'box-sizing: border-box;';
echo 'opacity: 0.5;';
echo 'transition: all 0.3s ease;';
echo '}';
echo '';
echo 'input[type="file"] {';
echo 'background-color: white;';
echo '}';
echo '';
echo 'input[type="file"]::file-selector-button {';
echo 'background-color: #854d28;';
echo 'color: #fff;';
echo 'padding: 10px;';
echo 'border: none;';
echo 'border-radius: 5px;';
echo 'cursor: pointer;';
echo 'margin-right:10px;';
echo '/* font-size: 16px; */';
echo 'transition: background-color 0.3s ease;';
echo '}';
echo '';
echo 'input[type="file"]::file-selector-button:hover {';
echo 'background-color: #6e4225;';
echo '}';
echo '';
echo 'input[type="text"]:focus,';
echo 'input[type="email"]:focus,';
echo 'input[type="datetime-local"]:focus,';
echo 'input[type="file"]:focus,';
echo 'textarea:focus,';
echo 'select:focus {';
echo 'border-color: #ddd;';
echo 'outline: none;';
echo '}';
echo '';
echo 'textarea {';
echo 'height: 100px;';
echo 'resize: vertical;';
echo '}';
echo '';
echo '.buttons {';
echo 'display: flex;';
echo 'justify-content: center;';
echo '}';
echo '';
echo '.buttons button {';
echo 'background-color: #854d28;';
echo 'color: #fff;';
echo 'padding: 10px 20px;';
echo 'border: none;';
echo 'border-radius: 5px;';
echo 'width: 150px;';
echo 'font-size: 16px;';
echo 'cursor: pointer;';
echo 'margin-right: 10px;';
echo '}';
echo '';
echo '.buttons button:hover {';
echo 'background-color: #6e4225;';
echo '}';
echo '.cgpa {';
echo 'width: 100%;';
echo 'padding: 10px;';
echo 'margin-bottom: 20px;';
echo 'border: 1px solid #ddd;';
echo 'border-radius: 5px;';
echo 'box-sizing: border-box;';
echo 'opacity: 0.5;';
echo '}';
echo '</style>';
echo '<script defer src="registration.js"></script>';
echo '</head>';
echo '<body style="background-color: #000;">';
echo '<link rel="stylesheet" href="design.css">';
echo '<form>';
echo '<h2>ON-DUTY REGISTRATION FORM</h2>';
echo '';
echo '<label for="first-name">First Name(With Initial):</label>';
echo '<input type="text" id="first-name" name="first-name" required>';
echo '';
echo '<label for="register-number">Register Number:</label>';
echo '<input type="text" id="register-number" name="register-number" required>';
echo '';
echo '<label for="email">Email Address:</label>';
echo '<input type="email" id="email" name="email" required>';
echo '';
echo '<label>Enter Your CGPA</label>';
echo '<input type="number" class="cgpa" max="10" min="6" step="0.1" required>';
echo '';
echo '<label for="start-date">Event Start Date:</label>';
echo '<input type="datetime-local" id="start-date" name="start-date" class="datetime" required>';
echo '';
echo '<label for="end-date">Event End Date:</label>';
echo '<input type="datetime-local" id="end-date" name="end-date" class="datetime" required>';
echo '';
echo '<label for="file1">Upload File1:</label>';
echo '<input type="file" class="file1" name="file1" required>';
echo '';
echo '<label for="file2">Upload File2:</label>';
echo '<input type="file" class="file1" name="file2" required>';
echo '';
echo '<label for="description">Description:</label>';
echo '<textarea id="description" maxlength="250" style="font-size: medium;color: black;"></textarea>';
echo '';
echo '<div class="buttons">';
echo '<button type="reset">Reset</button>';
echo '<button type="submit">Submit</button>';
echo '</div>';
echo '</form>';
echo '';
// echo '<script>';
// echo '// Validate description word count';
// echo 'document.querySelector('form').addEventListener('submit', function (e) {';
// echo 'const description = document.getElementById('description').value.trim();';
// echo 'const wordCount = description.split(/\s+/).length;';
// echo 'if (wordCount < 9 || wordCount > 250) {';
// echo 'alert('Description must be between 9 and 250 words.');';
// echo 'e.preventDefault();';
// echo '}';
// echo '});';
// echo '';
// echo '// Check uploaded files';
// echo 'const fileInputs = document.querySelectorAll('input[type="file"]');';
// echo 'fileInputs.forEach(input => {';
// echo 'input.addEventListener('change', function () {';
// echo 'if (this.files.length > 0) {';
// echo 'const fileName = this.files[0].name;';
// echo 'if (confirm(`Is this the correct file: ${fileName}?`) === false) {';
// echo 'this.value = ''; // Clear the file input';
// echo '}';
// echo '}';
// echo '});';
// echo '});';
// echo '</script>';
echo '</body>';
echo '</html>';
echo '';
?>
</body>
</html>